"""
Statistical test script using Friedman test and Nemenyi post-hoc analysis.
Generates and saves the Critical Difference (CD) diagram.
Reads the merged results matrix generated by the preparation script.
"""

import os
import pandas as pd
from scipy.stats import friedmanchisquare
import scikit_posthocs as sp
from matplotlib import pyplot as plt
from argparse import ArgumentParser

def statistical_test(df: pd.DataFrame, save_dir: str):
    columns = [df.iloc[:, i] for i in range(df.shape[1])]
    
    print("--- Friedman Test Result ---")
    print(friedmanchisquare(*columns))
    
    nemenyi_res = sp.posthoc_nemenyi_friedman(df)
    print("\n--- Nemenyi Post-hoc P-values ---")
    print(nemenyi_res)
    
    ranks = df.rank(axis=1)
    avg_ranks = ranks.mean()
    print("\n--- Average Ranks ---")
    print(avg_ranks)
    
    # Set a wider canvas size to ensure labels on the left and right fit properly
    plt.figure(figsize=(12, 5))
    
    sp.critical_difference_diagram(avg_ranks, nemenyi_res)
    
    os.makedirs(save_dir, exist_ok=True)
    save_path = os.path.join(save_dir, 'cd_diagram.png')
    
    # Prevent cropping with bbox_inches='tight' and add extra horizontal padding
    plt.savefig(save_path, dpi=300, bbox_inches='tight', pad_inches=0.5)
    print(f"\nPlot successfully saved to: {save_path}")
    
    plt.show()

def main():
    parser = ArgumentParser(description="Run Friedman & Nemenyi tests and generate CD plot.")
    parser.add_argument('-i', '--input_csv', type=str, required=True, help="Path to the merged matrix CSV file")
    parser.add_argument('-o', '--out_dir', type=str, required=True, help="Directory to save the CD plot")
    args = parser.parse_args()

    file_path = args.input_csv
    save_dir = args.out_dir
    
    try:
        df = pd.read_csv(file_path)
    except FileNotFoundError:
        print(f"Error: Could not find {file_path}. Please run the preparation script first.")
        return
        
    # Extract only algorithm cost data by excluding the 'instance' column (index 0)
    df_costs = df.iloc[:, 1:]
    
    print("Data preview for statistical test:")
    print(df_costs.head())
    
    statistical_test(df_costs, save_dir)

if __name__ == "__main__":
    main()